import { Colors } from '@/constants/Colors';
import Fonts from '@/constants/Fonts';
import { Normalize } from '@/constants/Normalize';
import { Dimensions, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  ownBubbleContainer: {
    backgroundColor: Colors.chatBubbleGreen,
    maxWidth: Dimensions.get('screen').width * 0.7,
    minWidth: 0,
    alignSelf: 'flex-end',
    borderRadius: Normalize(8),
    marginRight: Normalize(15),
  },
  otherBubbleContainer: {
    backgroundColor: Colors.chatBubbleGray,
    maxWidth: Dimensions.get('screen').width * 0.7,
    minWidth: 0,
    alignSelf: 'flex-start',
    borderRadius: Normalize(8),
    marginLeft: Normalize(15),
  },
  tailMainContainer: {
    position: 'absolute',
    bottom: Normalize(-2),
    justifyContent: 'flex-end',
    top: 0,
    zIndex: Normalize(-1),
  },
  tailOwnContainer: {
    left: 0,
    right: Normalize(8),
    alignItems: 'flex-end',
  },
  tailOtherContainer: {
    left: 0,
    right: 0,
    alignItems: 'flex-start',
  },
  messageText: {
    color: Colors.white,
    fontFamily: Fonts.HelveticaNeueRegular,
    marginRight: Normalize(10),
    fontSize: Normalize(14),
  },
  timeStampContainer: {
    position: 'absolute',
    bottom: Normalize(5),
    right: Normalize(3),
    width: Normalize(60),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  timeStampText: {
    fontFamily: Fonts.HelveticaNeueRegular,
    fontSize: Normalize(11),
    color: Colors.white,
  },
  renderMultiOwnBubble: {
    padding: Normalize(5),
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.chatBubbleGreen,
    width: Dimensions.get('screen').width * 0.7,
    alignSelf: 'flex-end',
    borderRadius: Normalize(8),
    marginRight: Normalize(15),
    justifyContent: 'space-around',
  },
  renderMultiOtherBubble: {
    padding: Normalize(5),
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.chatBubbleGray,
    width: Dimensions.get('screen').width * 0.7,
    alignSelf: 'flex-start',
    borderRadius: Normalize(8),
    marginLeft: Normalize(15),
    justifyContent: 'space-around',
  },
  multiImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flexBasis: '48%',
    borderRadius: Normalize(5),
    overflow: 'hidden',
    width: (Dimensions.get('screen').width * 0.65) / 2,
    height: Dimensions.get('screen').height * 0.15,
  },
  multiImageStyle: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  countText: {
    color: 'white',
    fontSize: Normalize(20),
    backgroundColor: Colors.blurBlack,
    width: (Dimensions.get('screen').width * 0.65) / 2,
    height: Dimensions.get('screen').height * 0.15,
    position: 'absolute',
    textAlign: 'center',
    // textAlignVertical: 'center',
    paddingTop: '42%',
    fontFamily: Fonts.HelveticaNeueMedium,
  },
  linkTextStyle: {
    color: Colors.hyperlinkGreen,
    textDecorationLine: 'underline',
    fontSize: Normalize(14),
  },
  documentContainer: {
    width: Dimensions.get('screen').width * 0.6,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: Normalize(8),
    padding: Normalize(5),
    flexDirection: 'row',
  },
  documentName: {
    fontFamily: Fonts.HelveticaNeueRegular,
    color: Colors.white,
    fontSize: Normalize(12),
  },
  fileMetaInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Normalize(2),
  },
  fileSizeTypeText: {
    fontFamily: Fonts.HelveticaNeueRegular,
    fontSize: Normalize(10),
  },
  separateText: {
    fontFamily: Fonts.HelveticaNeueRegular,
    fontSize: Normalize(16),
    marginLeft: Normalize(5),
  },
  documentTimeContainer: {
    alignSelf: 'flex-end',
    marginTop: Normalize(5),
  },
});
